version: "3.5"
services:
  db:
    build: Docker/Database
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
  web:
    image: nginx:alpine
    volumes:
      - ./Docker/Nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./application:/application
    ports:
      - ${WEB_LOCAL_PORT_HTTP}:80
      - ${WEB_LOCAL_PORT_HTTPS}:443
    depends_on:
      - php
      - db
    networks:
      - frontend
      - backend
  php:
    build:
      context: ""
      dockerfile: Docker/PHP/Dockerfile
      args:
        - LOCAL_UID=${LOCAL_UID}
        - LOCAL_GID=${LOCAL_GID}
    working_dir: /application
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - ./application:/application
      - ./Docker/PHP/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./Docker/PHP/php-ini-overrides.ini:/usr/local/etc/php/conf.d/infaestructure-overrides.ini
    depends_on:
      - db
    networks:
      - backend

networks:
  frontend:
    name: custom_front
  backend:
    name: custom_backend